#!/usr/bin/env node
// scripts/reingest-stage5c.mjs
//
// Direct-to-Postgres re-ingest of the Stage 5c observations. Bypasses
// the HTTP /observations route because we're loading 1,603 person
// observations + their merge twins in one atomic pass.
//
// Two-phase load:
//   1. INSERT the person observations with client-minted UUIDs (using
//      INSERT ... ON CONFLICT (user_id, dedup_key) DO NOTHING).
//   2. INSERT the merge observations that reference those UUIDs; for
//      each, if a bridge lookup hits an existing person (Umayr/Ramon),
//      use that person_id; otherwise, generate a fresh UUID.
//   3. INSERT the person_observation_links rows.
//
// The schema's SECURITY DEFINER RPC is replicated here via direct SQL —
// we have the service DB URL in .env.local. Scoped to a single user_id.
//
// Emits outputs/stage-5c-reingest-2026-04-20/reingest-summary.json.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";

import { buildBridgeIndex, decideMergeTarget } from "./generate-merges-v2.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "..");
const OBS_FILE = resolve(
  REPO_ROOT,
  "outputs/stage-5c-reingest-2026-04-20/observations.ndjson",
);
const OUT_DIR = resolve(REPO_ROOT, "outputs/stage-5c-reingest-2026-04-20");
const SUMMARY_FILE = resolve(OUT_DIR, "reingest-summary.json");
mkdirSync(OUT_DIR, { recursive: true });

const USER_ID = "dbb398c2-1eff-4eee-ae10-bad13be5fda7";

function loadEnv() {
  const raw = readFileSync(resolve(REPO_ROOT, ".env.local"), "utf8");
  const env = Object.create(null);
  for (const line of raw.split("\n")) {
    if (!line || line.startsWith("#")) continue;
    const idx = line.indexOf("=");
    if (idx < 0) continue;
    env[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  }
  return env;
}

async function fetchExistingPersons(pool) {
  // Materialize the phones/emails for any existing (pre-wipe surviving)
  // persons by reading their linked person-observations. Same logic the
  // /persons/enriched endpoint will expose (Phase C1), but local.
  const res = await pool.query(
    `
    SELECT
      l.person_id AS id,
      COALESCE(array_agg(DISTINCT p ORDER BY p) FILTER (WHERE p IS NOT NULL), ARRAY[]::text[]) AS phones,
      COALESCE(array_agg(DISTINCT e ORDER BY e) FILTER (WHERE e IS NOT NULL), ARRAY[]::text[]) AS emails
    FROM person_observation_links l
    JOIN observations o ON o.id = l.observation_id
    LEFT JOIN LATERAL jsonb_array_elements_text(o.payload->'phones') AS p ON TRUE
    LEFT JOIN LATERAL jsonb_array_elements_text(o.payload->'emails') AS e ON TRUE
    WHERE o.user_id = $1
      AND o.kind = 'person'
    GROUP BY l.person_id
    `,
    [USER_ID],
  );
  return res.rows;
}

function readNdjson(path) {
  return readFileSync(path, "utf8")
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => JSON.parse(l));
}

async function main() {
  const env = loadEnv();
  const pool = new pg.Pool({
    connectionString: env.SUPABASE_DB_URL,
    max: 4,
  });

  const existing = await fetchExistingPersons(pool);
  const bridgeIndex = buildBridgeIndex(existing);
  console.error(
    `[reingest] bridge index: ${bridgeIndex.size} entries from ${existing.length} persons`,
  );

  const personObs = readNdjson(OBS_FILE);
  console.error(`[reingest] loaded ${personObs.length} person observations`);

  // Assign a fresh UUID to every person-observation client-side so we can
  // reference it in the merge payload without a round-trip.
  const planned = personObs.map((obs) => {
    const decision = decideMergeTarget(obs, bridgeIndex);
    if (decision.kind === "conflict") {
      return { obs, obsId: randomUUID(), decision, skip: true };
    }
    return {
      obs,
      obsId: randomUUID(),
      decision,
      skip: false,
    };
  });

  const conflicts = planned.filter((p) => p.skip);
  const toLoad = planned.filter((p) => !p.skip);
  console.error(`[reingest] to_load=${toLoad.length} conflicts=${conflicts.length}`);

  // Cut into batches of 500 for pg insert efficiency.
  const BATCH = 500;
  let insertedObs = 0;
  let insertedMerges = 0;
  let insertedLinks = 0;
  let dedupedObs = 0;

  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    for (let i = 0; i < toLoad.length; i += BATCH) {
      const chunk = toLoad.slice(i, i + BATCH);

      // Insert person observations. Use client-minted id column.
      // dedup_key is generated by a trigger; INSERT ... ON CONFLICT handles it.
      const obsValues = [];
      const obsParams = [];
      let pi = 1;
      for (const p of chunk) {
        obsValues.push(
          `($${pi}, $${pi + 1}, $${pi + 2}, $${pi + 3}, 'wazowski', $${pi + 4}, $${pi + 5}, $${pi + 6}, $${pi + 7}, $${pi + 8}::jsonb)`,
        );
        obsParams.push(
          p.obsId,
          USER_ID,
          p.obs.observed_at,
          new Date().toISOString(),
          p.obs.kind,
          p.obs.evidence_pointer,
          p.obs.confidence,
          p.obs.reasoning,
          JSON.stringify(p.obs.payload),
        );
        pi += 9;
      }
      const obsSql = `
        INSERT INTO observations
          (id, user_id, observed_at, ingested_at, observer, kind, evidence_pointer, confidence, reasoning, payload)
        VALUES ${obsValues.join(",")}
        ON CONFLICT (user_id, dedup_key) DO NOTHING
        RETURNING id
      `;
      const obsRes = await client.query(obsSql, obsParams);
      insertedObs += obsRes.rowCount;
      dedupedObs += chunk.length - obsRes.rowCount;

      // Build merge envelopes for this chunk.
      const mergeValues = [];
      const mergeParams = [];
      const linkValues = [];
      const linkParams = [];
      let mi = 1;
      let li = 1;
      for (const p of chunk) {
        const personId =
          p.decision.kind === "existing"
            ? p.decision.person_id
            : p.decision.person_id;
        const mergeId = randomUUID();
        const bridges = [
          ...(p.obs.payload.phones ?? []).map((x) => `phone:${x}`),
          ...(p.obs.payload.emails ?? []).map((x) => `email:${String(x).toLowerCase()}`),
        ];
        const mergePayload = {
          person_id: personId,
          deterministic_bridges: bridges,
          merged_observation_ids: [p.obsId, p.obsId],
        };
        mergeValues.push(
          `($${mi}, $${mi + 1}, $${mi + 2}, $${mi + 3}, 'wazowski', 'merge', $${mi + 4}, 0.85, $${mi + 5}, $${mi + 6}::jsonb)`,
        );
        mergeParams.push(
          mergeId,
          USER_ID,
          p.obs.observed_at,
          new Date().toISOString(),
          `reingest-merge-20260420://${p.obsId}`,
          `Bridge-aware merge from Stage 5c reingest. Target person_id=${personId}.`,
          JSON.stringify(mergePayload),
        );
        mi += 7;

        // Link the person observation to the person (upsert person row first)
        linkValues.push(`($${li}, $${li + 1}, $${li + 2})`);
        linkParams.push(personId, p.obsId, mergeId);
        li += 3;
        // Also link the merge observation itself so it appears in card reads
        linkValues.push(`($${li}, $${li + 1}, $${li + 2})`);
        linkParams.push(personId, mergeId, mergeId);
        li += 3;
      }

      const mergeSql = `
        INSERT INTO observations
          (id, user_id, observed_at, ingested_at, observer, kind, evidence_pointer, confidence, reasoning, payload)
        VALUES ${mergeValues.join(",")}
        ON CONFLICT (user_id, dedup_key) DO NOTHING
        RETURNING id
      `;
      const mergeRes = await client.query(mergeSql, mergeParams);
      insertedMerges += mergeRes.rowCount;

      // Upsert persons rows (unique set from this chunk)
      const uniquePersonIds = [...new Set(chunk.map((p) => p.decision.person_id))];
      if (uniquePersonIds.length) {
        const personRes = await client.query(
          `INSERT INTO persons (id, user_id)
             SELECT unnest($1::uuid[]), $2::uuid
             ON CONFLICT (id) DO NOTHING`,
          [uniquePersonIds, USER_ID],
        );
        // rowCount reflects new persons created; not tracked separately
        void personRes;
      }

      // Insert links
      const linkSql = `
        INSERT INTO person_observation_links (person_id, observation_id, linked_by_observation_id)
        VALUES ${linkValues.join(",")}
        ON CONFLICT (person_id, observation_id) DO NOTHING
      `;
      const linkRes = await client.query(linkSql, linkParams);
      insertedLinks += linkRes.rowCount;

      console.error(
        `[reingest] batch ${i}/${toLoad.length} — obs+=${obsRes.rowCount} merges+=${mergeRes.rowCount} links+=${linkRes.rowCount}`,
      );
    }
    await client.query("COMMIT");
  } catch (e) {
    await client.query("ROLLBACK");
    throw e;
  } finally {
    client.release();
    await pool.end();
  }

  const summary = {
    total_person_obs_input: personObs.length,
    conflicts,
    conflicts_count: conflicts.length,
    inserted_person_obs: insertedObs,
    deduped_person_obs: dedupedObs,
    inserted_merge_obs: insertedMerges,
    inserted_links: insertedLinks,
    bridge_index_size: bridgeIndex.size,
    existing_person_count: existing.length,
  };
  writeFileSync(SUMMARY_FILE, JSON.stringify(summary, null, 2) + "\n");
  console.log(JSON.stringify(summary, null, 2));
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((e) => {
    console.error("reingest-stage5c failed:", e?.message ?? e);
    process.exit(1);
  });
}
